stages:
  - dependences
  - description
  - build
  - teste
  - imagem
  - upload


dependences:
  stage: dependences
  script:
    - ls
  after_script:
    echo "Dependências instaladas"

show_machine_config:
  stage: description
  before_script:
    - chmod +x ./ip.sh
  script:
    - echo "Configuranção do container onde está sendo rodado este ci:"
    - cat /etc/os-release
    - echo "IP:"
    - ./ip.sh
  after_script:
    - echo "informações ok..."



build_app:
  stage: build
  needs:
  - dependences
  script:
  - cat ./app/index.html

executar_teste:
  only:
    - test
  stage: teste
  before_script:
  - echo "Preparando testes..."
  script:
    - echo "Executando testes"
  after_script:
    - "apagando arquivos temporários"

criar_imagem:
  needs:
    - build_app
  only:
    - dev
    - test
    - main
  stage: imagem
  script:
    - echo "criando imagens"

push_imagens:
  needs:
    - criar_imagem
  only:
    - main
  stage: upload
  script:
  - echo "upload_pendente"
  
  after_script:
  - "upload completo"