stages:
  - description
  - teste
  - imagem
  - upload

show_machine_config:
  stage: description
  before_script:
    - chmod +x ./ip.sh
  script:
    - echo "Configuranção do container onde está sendo rodado este ci:"
    - cat /etc/os-release
    - echo "IP:"
    - ./ip.sh
  after_script:
    - echo "informações ok..."

executar_teste:
  stage: teste

  before_script:
  - echo "Preparando testes..."

  script:
    - echo "Executando testes"
  
  after_script:
    - "apagando arquivos temporários"

criar_imagem:
  stage: imagem
  script:
    - echo "criando imagens"

push_imagens:
  stage: upload
  needs:
    - criar_imagem
  script:
  - echo "upload_pendente"
  
  after_script:
  - "upload completo"
